### ISSUE TITLE
Realme xt app cleaner android accessibility issue

### ISSUE THREAD

**Issue by gokulyc** [d4rken/sdmaid-public#3040]
Realme xt has app cleaner android 
 accessibility issue. issue persists even after reenabling feature.

screenshot attached

![Screenshot_2019-10-17-12-45-19-28_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/13468848/66986433-8cf74f00-f0dc-11e9-966a-31e71e74fd83.png)

**Comment by d4rken** [comment]
Try rebooting.
If this happens regularly then the service is crashing and we need to find out why.

Start by providing your install ID (long press settings) or even better a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by gokulyc** [comment]
Install id :       
70537c17-c550-4a10-956d-27933396c8f1

**Comment by d4rken** [comment]
Try uploading the logfile to a filehoster and posting the link here.

**Comment by gokulyc** [comment]
Please find the link

https://drive.google.com/file/d/168LsxtKi-1ZcQ1p8HwYWBn6ZxekZ7gz7/view?usp=drivesdk

**Comment by d4rken** [comment]
I could not find a crash within the logs, but SD Maid failed to detect the correct storage entry to press. I've fixed that, it might be the underlying reason for the whole issue. Please reopen this ticket after the next beta, or mail me if you want to test this build early.

**Comment by gokulyc** [comment]
Still not working
![Screenshot_2019-11-01-08-57-35-86](https://user-images.githubusercontent.com/13468848/68000666-04a1ae00-fc87-11e9-9b60-79ae67b2b43b.png)
 
log file:

https://drive.google.com/file/d/18EwVxSdTntwYP2ji4o9jOcfQsiOE5cbo/view?usp=drivesdk

**Comment by gokulyc** [comment]
Hi,

Issue still not resolved.

issue tracker updated.

**Comment by d4rken** [comment]
The log does not contain what is shown on the screenshot.

Can you repeat the log? A debug log recording while SD Maid is stuck on the screen from your screenshot should be enough. You don't need to put the accessibility service into debug mode.

**Comment by gokulyc** [comment]
Please find required details below:

install id : 93afeb69-d4db-4fea-af05-89c3aac57b46


  sdmaid_logfile_1572578906451.txt
<https://drive.google.com/file/d/18rnDMJzVCuAzyGVWJA98aincY1FWoMvv/view?usp=drivesdk>

**Comment by d4rken** [comment]
SD Maid is looking for the app name on that window which isn't there on the Realme ROM. I've now removed that check for this type of ROM. If you'd like to test it before the next beta, mail me.
