### ISSUE TITLE
SD-card access on 4.0.10 beta

### ISSUE THREAD

**Issue by gaich** [d4rken/sdmaid-public#330]
SD Maid 4.0.10 shows me a prompt to grant SD Card access constantly, although the whole access was given using [Nextapp SDfix](https://play.google.com/store/apps/details?id=nextapp.sdfix) and there were no problems with previous versions.
![screenshot_2016-03-20-19-10-28](https://cloud.githubusercontent.com/assets/3396847/13904097/e9965d9a-eecf-11e5-9354-b9decc411e85.png)
You choose SDcard in the next window, but the app tells the input is invalid.
My phone is LG G4, H815, Lollipop 5.0.1, H815 [Genisys Rom 2.2.1](http://forum.xda-developers.com/g4/development/05-feb-2016-genisys-rom-2-2-lollipop-eu-t3309035) 

![screenshot_2016-03-20-19-05-30](https://cloud.githubusercontent.com/assets/3396847/13904099/2a1f8b3e-eed0-11e5-8f5b-7488df5127aa.png)
![screenshot_2016-03-20-19-05-23](https://cloud.githubusercontent.com/assets/3396847/13904100/2a209b6e-eed0-11e5-95eb-520eee070172.png)
![screenshot_2016-03-20-19-05-18](https://cloud.githubusercontent.com/assets/3396847/13904101/2a21c232-eed0-11e5-8668-df06e8812434.png)
![screenshot_2016-03-20-19-05-12](https://cloud.githubusercontent.com/assets/3396847/13904102/2a23ca32-eed0-11e5-88b8-94be7e5dc270.png)
![screenshot_2016-03-20-19-05-07](https://cloud.githubusercontent.com/assets/3396847/13904103/2a25781e-eed0-11e5-9e9c-dd998cd3074c.png)

[A screenrecord](https://youtu.be/Ayio3g188s4).

**Comment by d4rken** [comment]
Likely caused by #231.
4.0.10 fixed a few detection issues which is why you see the prompt, I think...
Can you record a debug run ?

SD Maid can still write to the card though, right ? (Because you have root)
Due to the sdfix app, can SD Maid also write without root? Try it by just not granting root to SD Maid.

The permission dialog is independent of the read/writeability tests.

**Comment by gaich** [comment]
SD Maid works fine, I just press skip.
[logs.zip](https://github.com/d4rken/sdmaid-public/files/181557/logs.zip)
But if I don`t grant root, it shows that Public storage (secondary) is read only.
![screenshot_2016-03-21-06-39-17](https://cloud.githubusercontent.com/assets/3396847/13908047/0c9a68c0-ef36-11e5-87b6-44efc7a20b91.png)
![screenshot_2016-03-21-06-39-01](https://cloud.githubusercontent.com/assets/3396847/13908049/12e50fa0-ef36-11e5-9e52-51086a139024.png)
![screenshot_2016-03-21-06-41-22](https://cloud.githubusercontent.com/assets/3396847/13908051/16eb4f74-ef36-11e5-844b-a15ec76f8184.png)
Without root I don`t know how to check SD Card write status, but I cannot, for the instance, change receivers` state for system apps.
[no root_logfile_1458513486040.zip](https://github.com/d4rken/sdmaid-public/files/181558/no.root_logfile_1458513486040.zip)

**Comment by d4rken** [comment]
Try to create and delete a folder as write test. Thanks for the log files,
I'm currently on mobile will check the logs later.
Am 21.03.2016 12:27 vorm. schrieb "gaich" <notifications@github.com>:

**Comment by gaich** [comment]
I am able to create and delete it without granting root permissions:
https://youtu.be/GzMeJHqyKkg
[sdmaid_logfile_1458570931278.zip](https://github.com/d4rken/sdmaid-public/files/182440/sdmaid_logfile_1458570931278.zip)

**Comment by d4rken** [comment]
Thanks for all the info.
Not being able to write to external storage despite the sdcard fix is due to a mistake I made in the write test function.

I think other tools than the explorer don't experience this bug though, can you confirm that ? Can the system cleaner delete items from the external sdcard without root ?

On a side note, from the logs it seems I might be able to fix the your case of the #231 issue :).

**Comment by gaich** [comment]
Yes, I easily managed to delete empty directories from external SD in System cleaner whithout granting root.
[sdmaid_logfile_1458730917389.zip](https://github.com/d4rken/sdmaid-public/files/185977/sdmaid_logfile_1458730917389.zip)
https://youtu.be/Oo1mcDwesoc
But without root System cleaner just shows two elements - Gallery thumbnails and Empty directories. When the root is granted, there are much more:
![screenshot_2016-03-23-20-43-01](https://cloud.githubusercontent.com/assets/3396847/13985523/3b0cf4e4-f138-11e5-896b-2c28d60ee3f3.png)

**Comment by d4rken** [comment]
Thanks, that confirms my suspicions.
Explorer and Overview should be fixed with the next update.
I'll also try something for the sdcard permission granting.

It's normal that the system cleaner results differ, some filters only work with root.

**Comment by gaich** [comment]
Thank you!

**Comment by prozacfield** [comment]
I have the same issue. Here's my logfile attached. 
[sdmaid_logfile_1458991539075.zip](https://github.com/d4rken/sdmaid-public/files/190468/sdmaid_logfile_1458991539075.zip)

**Comment by d4rken** [comment]
@prozacfield basically the same "light version" of issue #231 that @gaich has.
For further progress on that follow issue #231 as I will close this ticket when the write detection is fixed.

**Comment by prozacfield** [comment]
@d4rken thanks.

**Comment by d4rken** [comment]
Write test should be fixed with v4.0.11 and I think permission granting should also work for this case and similar ones (maybe all LG?).

**Comment by gaich** [comment]
4.011 - the prompt and input invalid issue still remain...
[sdmaid_logfile_1459204506710.txt](https://github.com/d4rken/sdmaid-public/files/192589/sdmaid_logfile_1459204506710.txt)

**Comment by d4rken** [comment]
I think I made a coding mistake, can you send me a mail and I'll give you a test version?

**Comment by gaich** [comment]
gaich@live.ru

**Comment by neojudgment** [comment]
Hi, exactly the same bug as gaich above !

**Comment by d4rken** [comment]
@neojudgment Please provide a debug log to see whether it is exactly the same issue. Some issues have the same symptons but are slightly different such that the fix employed for this case (LG specific?) doesn't apply and it's a more general issue as #231.
If it's the same issue and you mail me I can give you a test version too.

**Comment by neojudgment** [comment]
[sdmaid_logfile_1459263659863.txt](https://github.com/d4rken/sdmaid-public/files/193739/sdmaid_logfile_1459263659863.txt)

**Comment by d4rken** [comment]
@neojudgment It seems to be different from both this issue and #231. Both of your storages provide valid UUIDs:
```
StorageVolumeX: uuid: C5CF-8BA0 | state: mounted | path: /storage/sdcard0 | userlabel: FAT32
StorageVolumeX: uuid: 963B-07DF | state: mounted | path: /storage/sdcard1 | userlabel: M4_Note
StorageVolumeX: uuid: null | state: removed | path: /storage/usbotg | userlabel: null
```
I actually don't see SD Maid throwing any errors. If you want to pursue this further, please make a new ticket for this. (In that case you can also mail me and I'll give you a version that prints better logoutput for these kind of issues.

**Comment by gaich** [comment]
Test version works fine, no prompts or something of that kind.
[sdmaid_logfile_1459290273324.txt](https://github.com/d4rken/sdmaid-public/files/194440/sdmaid_logfile_1459290273324.txt)
]

**Comment by d4rken** [comment]
@gaich Can you clear SD Maids data and see if the prompt works correctly when granting the permission?

**Comment by gaich** [comment]
It works! No errors and invalid inputs.
![screenshot_2016-03-30-10-34-58](https://cloud.githubusercontent.com/assets/3396847/14129814/772a78fe-f668-11e5-8ca3-a14b82854711.png)

**Comment by prozacfield** [comment]
Issue solved, thank you very much.
